List of features involved:
    Understanding Data Processing
    Loading Different types of data
    Data Cleaning
    Slicing, Indexing, Manipulating and Cleaning Pandas Dataframe
    Working with Missing Data in Pandas
    Pandas 
    JSON
    
    SQL
        pysql
        mssql
        postgressql
    NoSQL
        MongoDB
    Sampling
    Wrangling
    
    Data Extraction
    Web Scraping

###### CSV files

In [1]:
# libraries
import pandas as pd

In [2]:
# Loading the data
path = "../data/sales.csv"
df = pd.read_csv(path)

###### Excel files

In [8]:
path = "../data/sales.xlsx"
df = pd.read_excel(path)

###### JSON files

In [12]:
# libraries
import json

In [13]:
path = "../data/sales.json"
with open(path,'r') as f:
    content = json.load(f)

In [1]:
# loading Data : Sklearn
from sklearn import datasets

In [19]:
data = datasets.load_breast_cancer(as_frame=True)

In [21]:
df = data['frame']

###### EDA : Exploratory Data Analysis

In [22]:
# Exploring the data
df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         569 non-null    float64
 15  compactness error        569 non-null    float64
 16  concavity error          569 non-null    float64
 17  concave points error     569 non-null    float64
 18  symmetry error           569 non-null    float64
 19  fractal dimension error  569 non-null    float64
 20  worst radius             569 non-null    float64
 21  worst texture            569 non-null    float64
 22  worst perimeter          569 non-null    float64
 23  worst area               569 non-null    float64
 24  worst smoothness         569 non-null    float64
 25  worst compactness        569 non-null    float64
 26  worst concavity          569 non-null    float64
 27  worst concave points     569 non-null    float64
 28  worst symmetry           569 non-null    float64
 29  worst fractal dimension  569 non-null    float64
 30  target                   569 non-null    int32
dtypes: float64(30), int32(1)
memory usage: 135.7 KB

In [24]:
df.describe(include='all')

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,0.062798,...,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946,0.627417
std,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,0.007060,...,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061,0.483918
min,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,0.049960,...,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040,0.000000
25%,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,0.057700,...,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460,0.000000
50%,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,0.061540,...,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040,1.000000
75%,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,0.066120,...,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080,1.000000
max,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,0.097440,...,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500,1.000000

###### Missing values

In [19]:
df.fillna(method = 'backfill')

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  58000.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  48.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [28]:
# interpolation
df.interpolate(method="slinear")

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  59500.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  41.5  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

###### Subsetting dataframe

In [34]:
df.loc[0:3,:]

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No

In [35]:
df.iloc[0:3,:]

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No

In [45]:
df.take(list(range(0,5)))

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [49]:
# replace
df.replace(to_replace=44,value=50)

   Country   Age   Salary Purchased
0   France  50.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

###### Sampling

In [26]:
# train test split
from sklearn.model_selection import train_test_split

In [42]:
target_column = "target"
x = df.drop([target_column],axis=1).values
y = df[[target_column]].values

In [47]:
# Stratified Sample
xtr,xts,ytr,yts = train_test_split(x,y,stratify=y)

In [63]:
# Random Sampling 
import numpy as np
random_indices = np.random.choice(df.index,replace = False,size=len(df))

In [65]:
random_sample  = df.iloc[random_indices]

In [67]:
random_sample

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
392,15.490,19.97,102.40,744.7,0.11600,0.15620,0.18910,0.091130,0.1929,0.06744,...,29.41,142.10,1359.0,0.1681,0.39130,0.55530,0.21210,0.3187,0.10190,0
376,10.570,20.22,70.15,338.3,0.09073,0.16600,0.22800,0.059410,0.2188,0.08450,...,22.82,76.51,351.9,0.1143,0.36190,0.60300,0.14650,0.2597,0.12000,1
81,13.340,15.86,86.49,520.0,0.10780,0.15350,0.11690,0.069870,0.1942,0.06902,...,23.19,96.66,614.9,0.1536,0.47910,0.48580,0.17080,0.3527,0.10160,1
254,19.450,19.33,126.50,1169.0,0.10350,0.11880,0.13790,0.085910,0.1776,0.05647,...,24.57,163.10,1972.0,0.1497,0.31610,0.43170,0.19990,0.3379,0.08950,0
212,28.110,18.47,188.50,2499.0,0.11420,0.15160,0.32010,0.159500,0.1648,0.05525,...,18.47,188.50,2499.0,0.1142,0.15160,0.32010,0.15950,0.1648,0.05525,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
373,20.640,17.35,134.80,1335.0,0.09446,0.10760,0.15270,0.089410,0.1571,0.05478,...,23.17,166.80,1946.0,0.1562,0.30550,0.41590,0.21120,0.2689,0.07055,0
275,11.890,17.36,76.20,435.6,0.12250,0.07210,0.05929,0.074040,0.2015,0.05875,...,18.99,79.46,472.4,0.1359,0.08368,0.07153,0.08946,0.2220,0.06033,1
467,9.668,18.10,61.06,286.3,0.08311,0.05428,0.01479,0.005769,0.1680,0.06412,...,24.62,71.11,380.2,0.1388,0.12550,0.06409,0.02500,0.3057,0.07875,1
113,10.510,20.19,68.64,334.2,0.11220,0.13030,0.06476,0.030680,0.1922,0.07782,...,22.75,72.62,374.4,0.1300,0.20490,0.12950,0.06136,0.2383,0.09026,1
71,8.888,14.64,58.79,244.0,0.09783,0.15310,0.08606,0.028720,0.1902,0.08980,...,15.67,62.56,284.4,0.1207,0.24360,0.14340,0.04786,0.2254,0.10840,1

In [68]:
# Systematic Sampling
step = 5
random_indices = np.arange(1,len(df),step)
random_sample  = df.iloc[random_indices]

In [69]:
random_sample

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
1,20.570,17.77,132.90,1326.0,0.08474,0.07864,0.086900,0.070170,0.1812,0.05667,...,23.41,158.80,1956.0,0.12380,0.18660,0.24160,0.18600,0.2750,0.08902,0
6,18.250,19.98,119.60,1040.0,0.09463,0.10900,0.112700,0.074000,0.1794,0.05742,...,27.66,153.20,1606.0,0.14420,0.25760,0.37840,0.19320,0.3063,0.08368,0
11,15.780,17.89,103.60,781.0,0.09710,0.12920,0.099540,0.066060,0.1842,0.06082,...,27.28,136.50,1299.0,0.13960,0.56090,0.39650,0.18100,0.3792,0.10480,0
16,14.680,20.13,94.74,684.5,0.09867,0.07200,0.073950,0.052590,0.1586,0.05922,...,30.88,123.40,1138.0,0.14640,0.18710,0.29140,0.16090,0.3029,0.08216,0
21,9.504,12.44,60.34,273.9,0.10240,0.06492,0.029560,0.020760,0.1815,0.06905,...,15.66,65.13,314.9,0.13240,0.11480,0.08867,0.06227,0.2450,0.07773,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
546,10.320,16.35,65.31,324.9,0.09434,0.04994,0.010120,0.005495,0.1885,0.06201,...,21.77,71.12,384.9,0.12850,0.08842,0.04384,0.02381,0.2681,0.07399,1
551,11.130,22.44,71.49,378.4,0.09566,0.08194,0.048240,0.022570,0.2030,0.06552,...,28.26,77.80,436.6,0.10870,0.17820,0.15640,0.06413,0.3169,0.08032,1
556,10.160,19.59,64.73,311.7,0.10030,0.07504,0.005025,0.011160,0.1791,0.06331,...,22.88,67.88,347.3,0.12650,0.12000,0.01005,0.02232,0.2262,0.06742,1
561,11.200,29.37,70.67,386.0,0.07449,0.03558,0.000000,0.000000,0.1060,0.05502,...,38.30,75.19,439.6,0.09267,0.05494,0.00000,0.00000,0.1566,0.05905,1
566,16.600,28.08,108.30,858.1,0.08455,0.10230,0.092510,0.053020,0.1590,0.05648,...,34.12,126.70,1124.0,0.11390,0.30940,0.34030,0.14180,0.2218,0.07820,0

In [75]:
df.sample(5)

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
145,11.90,14.65,78.11,432.8,0.11520,0.12960,0.03710,0.030030,0.1995,0.07839,...,16.51,86.26,509.6,0.1424,0.25170,0.09420,0.06042,0.2727,0.10360,1
506,12.22,20.04,79.47,453.1,0.10960,0.11520,0.08175,0.021660,0.2124,0.06894,...,24.17,85.13,515.3,0.1402,0.23150,0.35350,0.08088,0.2709,0.08839,1
135,12.77,22.47,81.72,506.3,0.09055,0.05761,0.04711,0.027040,0.1585,0.06065,...,33.37,92.04,653.6,0.1419,0.15230,0.21770,0.09331,0.2829,0.08067,0
316,12.18,14.08,77.25,461.4,0.07734,0.03212,0.01123,0.005051,0.1673,0.05649,...,16.47,81.60,513.1,0.1001,0.05332,0.04116,0.01852,0.2293,0.06037,1
413,14.99,22.11,97.53,693.7,0.08515,0.10250,0.06859,0.038760,0.1944,0.05913,...,31.55,110.20,867.1,0.1077,0.33450,0.31140,0.13080,0.3163,0.09251,1

In [78]:
# Cluster Sampling
size = 50
sample = df.sample(size)

In [89]:
# Weighted Sample
def get_weighted_sample(df,n):
    def get_class_prob(x):
        weight_x = int(np.rint(n * len(x[x.target != 0]) / len(df[df.target != 0])))
        sampled_x = x.sample(weight_x).reset_index(drop=True)
        return (sampled_x)
        # we are grouping by the target class we use for the proportions

    weighted_sample = df.groupby('target').apply(get_class_prob)
    print(weighted_sample["target"].value_counts())
    return (weighted_sample)

sample = get_weighted_sample(df,100)

1    100
Name: target, dtype: int64

           mean radius  mean texture  mean perimeter  mean area  \
target
1      0         12.30         19.02           77.88      464.4
       1         12.77         21.41           82.02      507.4
       2         11.45         20.97           73.81      401.5
       3         12.62         17.15           80.62      492.9
       4         13.20         17.43           84.13      541.6
...                ...           ...             ...        ...
       95        10.49         18.61           66.86      334.3
       96        13.59         21.84           87.16      561.0
       97        12.67         17.30           81.25      489.9
       98        10.51         23.09           66.85      334.2
       99        13.15         15.34           85.31      538.9

           mean smoothness  mean compactness  mean concavity  \
target
1      0           0.08313           0.04202        0.007756
       1           0.08749           0.06601        0.031120
       2           0.11020           0.09362        0.045910
       3           0.08583           0.05430        0.029660
       4           0.07215           0.04524        0.043360
...                    ...               ...             ...
       95          0.10680           0.06678        0.022970
       96          0.07956           0.08259        0.040720
       97          0.10280           0.07664        0.031930
       98          0.10150           0.06797        0.024950
       99          0.09384           0.08498        0.092930

           mean concave points  mean symmetry  mean fractal dimension  ...  \
target                                                                 ...
1      0              0.008535         0.1539                 0.05945  ...
       1              0.028640         0.1694                 0.06287  ...
       2              0.022330         0.1842                 0.07005  ...
       3              0.022720         0.1799                 0.05826  ...
       4              0.011050         0.1487                 0.05635  ...
...                        ...            ...                     ...  ...
       95             0.017800         0.1482                 0.06600  ...
       96             0.021420         0.1635                 0.05859  ...
       97             0.021070         0.1707                 0.05984  ...
       98             0.018750         0.1695                 0.06556  ...
       99             0.034830         0.1822                 0.06207  ...

           worst texture  worst perimeter  worst area  worst smoothness  \
target
1      0           28.46            84.53       544.3           0.12220
       1           23.50            89.04       579.5           0.09388
       2           32.16            84.53       525.1           0.15570
       3           22.15            91.62       633.5           0.12250
       4           27.82            88.28       602.0           0.11010
...                  ...              ...         ...               ...
       95          24.54            70.76       375.4           0.14130
       96          30.04            97.66       661.5           0.10050
       97          21.10            88.70       574.4           0.13840
       98          24.22            70.10       362.7           0.11430
       99          20.50            97.67       677.3           0.14780

           worst compactness  worst concavity  worst concave points  \
target
1      0             0.09052          0.03619               0.03983
       1             0.08978          0.05186               0.04773
       2             0.16760          0.17550               0.06127
       3             0.15170          0.18870               0.09851
       4             0.15080          0.22980               0.04970
...                      ...              ...                   ...
       95            0.10440          0.08423               0.06528
       96            0.17300          0.14530               0.06189
       97            0.12120          0.10200               0.05602
       98            0.08614          0.04158               0.03125
       99            0.22560          0.30090               0.09722

           worst symmetry  worst fractal dimension  target
target
1      0           0.2554                  0.07207       1
       1           0.2179                  0.06871       1
       2           0.2762                  0.08851       1
       3           0.3270                  0.07330       1
       4           0.2767                  0.07198       1
...                   ...                      ...     ...
       95          0.2213                  0.07842       1
       96          0.2446                  0.07024       1
       97          0.2688                  0.06888       1
       98          0.2227                  0.06777       1
       99          0.3849                  0.08633       1

[100 rows x 31 columns]

In [96]:
sample = sample.reset_index(drop=True)

In [97]:
sample

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,12.30,19.02,77.88,464.4,0.08313,0.04202,0.007756,0.008535,0.1539,0.05945,...,28.46,84.53,544.3,0.12220,0.09052,0.03619,0.03983,0.2554,0.07207,1
1,12.77,21.41,82.02,507.4,0.08749,0.06601,0.031120,0.028640,0.1694,0.06287,...,23.50,89.04,579.5,0.09388,0.08978,0.05186,0.04773,0.2179,0.06871,1
2,11.45,20.97,73.81,401.5,0.11020,0.09362,0.045910,0.022330,0.1842,0.07005,...,32.16,84.53,525.1,0.15570,0.16760,0.17550,0.06127,0.2762,0.08851,1
3,12.62,17.15,80.62,492.9,0.08583,0.05430,0.029660,0.022720,0.1799,0.05826,...,22.15,91.62,633.5,0.12250,0.15170,0.18870,0.09851,0.3270,0.07330,1
4,13.20,17.43,84.13,541.6,0.07215,0.04524,0.043360,0.011050,0.1487,0.05635,...,27.82,88.28,602.0,0.11010,0.15080,0.22980,0.04970,0.2767,0.07198,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,10.49,18.61,66.86,334.3,0.10680,0.06678,0.022970,0.017800,0.1482,0.06600,...,24.54,70.76,375.4,0.14130,0.10440,0.08423,0.06528,0.2213,0.07842,1
96,13.59,21.84,87.16,561.0,0.07956,0.08259,0.040720,0.021420,0.1635,0.05859,...,30.04,97.66,661.5,0.10050,0.17300,0.14530,0.06189,0.2446,0.07024,1
97,12.67,17.30,81.25,489.9,0.10280,0.07664,0.031930,0.021070,0.1707,0.05984,...,21.10,88.70,574.4,0.13840,0.12120,0.10200,0.05602,0.2688,0.06888,1
98,10.51,23.09,66.85,334.2,0.10150,0.06797,0.024950,0.018750,0.1695,0.06556,...,24.22,70.10,362.7,0.11430,0.08614,0.04158,0.03125,0.2227,0.06777,1
99,13.15,15.34,85.31,538.9,0.09384,0.08498,0.092930,0.034830,0.1822,0.06207,...,20.50,97.67,677.3,0.14780,0.22560,0.30090,0.09722,0.3849,0.08633,1